import * as mongodb from 'mongodb';

export interface Donation {
  _id?: mongodb.ObjectId; // Automatically generated by MongoDB.
  donorName: string;
  donorEmail: string;
  merchantRequestId: string; // From Daraja API synchronous response.
  checkoutRequestId: string; // From Daraja API synchronous response.
  amount: number; // The amount paid by the customer.
  receiptNumber: string; // M-Pesa receipt number from CallbackMetadata.
  transactionDate: Date; // Payment date and time, parsed from CallbackMetadata.
  phoneNumber: string; // Customer phone number from CallbackMetadata. (decide if capture from user or daraja api)
  status: string; // E.g., "SUCCESS", "FAILED", or "PENDING".
  resultCode: number; // Numeric response code from the callback (0 for success).
  resultDesc: string; // Human-readable message explaining the payment status.
  createdAt?: Date; // When the payment document was created in your database.
  updatedAt: Date;
};

// Still needs to be completed, amount of data type number
// then consider numbers starting with +254 , or 07
// ask users to enter numbers without +254
export const donationSchema = {
  $jsonSchema: {
    bsonType: 'object',
    required: ['donorName', 'donorEmail', 'amount', 'phoneNumber', 'createdAt', 'updatedAt'],
    properties: {
      _id: {
        bsonType: 'objectId',
        description: 'Unique id for a donation in MongoDb'
      },
      donorName: {
        bsonType: 'string',
        description: 'Name for the person making a donation'
      },
      donorEmail: {
        bsonType: 'string',
        description: 'Email address for the person making a donation'
      },
      amount: {
        bsonType: 'double',
        description: 'The amount to be donated'
      },
      phoneNumber: {
        bsonType: 'string',
        description: 'The contact of the person making a donation'
      },
      createdAt: {
        bsonType: 'date',
        description: 'Date the donation was made',
      },
      updatedAt: {
        bsonType: 'date',
        description: 'Date when the donation was last updated',
      }
    }
  }
};